# Generated by Django 5.0a1 on 2023-11-01 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fire_vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('dispatch_time', models.TimeField()),
                ('incident', models.CharField(max_length=225)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/depot_departure_images')),
                ('manning', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ManyToManyField(to='fire_vehicle.firevehicle')),
            ],
        ),
    ]
