# Generated by Django 5.0a1 on 2023-11-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot_departure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depotdeparture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='depot_departure_images'),
        ),
    ]
