# Generated by Django 5.0a1 on 2023-10-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firevehicle',
            name='inspection_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='firevehicle',
            name='insurance_date',
            field=models.DateField(blank=True),
        ),
    ]
