# Generated by Django 5.0a1 on 2023-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_name',
            field=models.CharField(choices=[('STRAŻAK', 'STRAŻAK'), ('DOWÓDCA', 'DOWÓDCA'), ('KIEROWCA', 'KIEROWCA'), ('KPP', 'KPP'), ('RATOWNICTWO TECHNICZNE', 'RATOWNICTWO TECHNICZNE')], max_length=100),
        ),
    ]
