# Generated by Django 5.0a1 on 2023-10-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_details', '0005_alter_medicalcheckup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='emergency_permission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='permission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcheckup',
            name='blood_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='smokebox',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
